language: node_js
node_js:
  - "6.9.2"
dist: trusty
before_install:
  - npm i -g npm@5.6.0
  - git submodule update --init --recursive
  - git fetch origin master:refs/remotes/origin/master --depth=1
addons:
  chrome: stable
install:
  - npm install

script:
  - npm run ci

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
  - "node_modules"
